---
# Add a file or template to the snmp config directory
# copy the config parts the remote temp dir
# Note that the template files are passed in without the .j2 suffix
- name: Create SNMP config fragments tmp dir.
  ansible.builtin.tempfile:
    state: directory
    suffix: snmp_fragments 
  register: snmp_tmp_dir

- name: Add SNMP Config fragments
  template:
    src: "{{ snmp_templates_dir }}/{{ item }}.j2"
    dest: "{{ snmp_tmp_dir.path }}/{{ item }}"
  with_items: "{{ snmp_config_template_files }}"
  become: yes

- name: Assemble SNMP Config fragments
  ansible.builtin.assemble:
    src: "{{ snmp_tmp_dir.path }}"
    dest: "{{ base_install_dir }}/snmp/config/snmp.yml"
    owner: "{{ prom_user_name }}"
    group: "{{ prom_group_name }}"
  become: yes