---
# BLACKBOX
- name: "Add Blackbox default config."
  copy: 
    backup: yes
    src: '{{ blackbox_files_dir }}/blackbox_config.yml'
    dest: "{{ base_install_dir }}/blackbox/config/blackbox.yml"
    owner: "{{ prom_user_name }}"
    group: "{{ prom_group_name }}"

  become: yes