---
# - hosts: all
#   tags: base
#   become: true
#   vars:
#     docker_compose_ver: 1.25.5
#   roles:
#     - base

# Installing Packetbeat on nodes
- hosts: packetbeats
  tags: packetbeat
  roles:
    - packetbeat
