---
- name: Remove Filebeats
  hosts: filebeats
  tags: filebeat
  tasks:
    - name: Remove docker-compose for Filebeats
      shell: docker-compose down
      args:
        chdir: /opt/beats/
# # Installing Packetbeat on nodes
# - hosts: packetbeats
#   become: true
#   tags: packetbeat
#   roles:
#     - packetbeat
