---
- name: Stop Filebeats
  hosts: filebeats
  tags: filebeat
  tasks:
    - name: Stop docker-compose for Filebeats
      shell: docker-compose stop
      args:
        chdir: /opt/beats/
# # Installing Packetbeat on nodes
# - hosts: packetbeats
#   become: true
#   tags: packetbeat
#   roles:
#     - packetbeat
