
modules:
  PowerNet:
    walk: 
 #     - 1.3.6.1.4.1.318.1.3.4.6
      # - battManIdent
      # - dcPower
      # - universalInputOutput
      # - apc
#      - battManStringVoltage

     ##
      # For reasons that I don't understand, specifying the OID results in errors like this:
      #   level=error caller=main.go:130 msg="Error generating config netsnmp" err="cannot find oid '.1.3.6.1.4.1.318.1.1.12.1.15.0' to walk"
      # But the path '.1.3.6.1.4.1.318.1.1.12.1.15.0' maps to rPDUIdentDeviceLinetoLineVoltage.0
      # So specify that by name and the error goes away :/
      ##
      - rPDULoadStatusLoad  # Current
      - rPDUIdentDeviceRating
      - rPDUStatusPhaseState
      - rPDUIdentDeviceLinetoLineVoltage # .1.3.6.1.4.1.318.1.1.12.1.15.0
      - rPDUIdentDevicePowerWatts        # .1.3.6.1.4.1.318.1.1.12.1.16.0
      - rPDUIdentDevicePowerVA           # .1.3.6.1.4.1.318.1.1.12.1.18.0
      - rPDULoadStatusTable              # .1.3.6.1.4.1.318.1.1.12.2.3.1

      - rPDULoadDevOutletIndex
      
      # ?? does not report power at outlet so maybe that is why it is crashing 
      - rPDUOutletStatusLoad
      - rPDU2OutletMeteredStatusEntry
      #- rPDUOutletConfigOutletName

      #- rPDUOutletConfigEntry
      #- rPDUOutletConfigMonitoredEntry
      - rPDUOutletStatusEntry

    auth:
      community: "{{ snmp_community_string }}"
 