# Check if docker-compose is installed
- name: Check if Docker Compose is installed
  shell: command -v docker-compose >/dev/null 2>&1
  register: is_docker_compose_install

# If docker-compose is not installed, quit
- name: Exit if docker-compose is missing
  fail: msg="docker-compose is missing"
  when: is_docker_compose_install.rc != 0

- block:
  - name: Ensure docker daemon is started and enabled
    systemd:
      name: docker
      enabled: true
      state: 'started'
  when: component_type == 'worker'


# Copy required files
- name: Copy required files
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "docker-compose.yml", dest: "/opt/beats/" }
    - { src: "{{ '../../files/' + hostvars[inventory_hostname]['intermediate_certificate_name'] }}", dest: "/opt/beats/" }

# Copy the filebeat.yml
- name: Copy Filebeat template file
  become: true
  template:
    src: filebeat.yml.j2
    dest: /opt/beats/filebeat-docker.yml

# Start Filebeat
- name: Start Filebeat
  community.docker.docker_compose:
    project_src: /opt/beats
    project_name: fabric_beats_filebeat
    state: started
    build: true
  register: output

- name: Check if service is running
  ansible.builtin.assert:
    that:
      - "output.services.fabric_beats_filebeat.state.running"

  # shell: docker-compose up -d filebeat
  # args:
  #   chdir: /opt/beats/