---
# Add a file or template to the nginx config directory
# TODO figure out/decide how to remove a file.
- name: Add NGINX Config File
  template:
    src: "{{ nginx_template_dir }}/{{ item }}.j2"
    dest: "{{ base_install_dir }}/nginx/config/{{ item }}"
    owner: "{{ prom_user_name }}"
    group: "{{ prom_group_name }}"
  with_items: "{{ nginx_config_template_files }}"
  become: yes