---
# Add a thanos ruler rule files 
- name: Add Thanos ruler rule files.
  ansible.builtin.copy:
    src: "{{ thanos_alert_rule_file_dir }}/{{ item }}"
    dest: "{{ base_install_dir }}/thanos/rules/{{ item }}"
    owner: "{{ prom_user_name }}"
    group: "{{ prom_group_name }}"
  with_items: "{{ thanos_ruler_files | default(omit) }}"
  become: yes

# Add a thanos ruler rule templates 
# Note that the template files are passed in without the .j2 suffix
- name: Add Thanos ruler rule files.
  ansible.builtin.template:
    src: "{{ thanos_alert_rule_template_dir }}/{{ item }}.j2"
    dest: "{{ base_install_dir }}/thanos/rules/{{ item }}"
    owner: "{{ prom_user_name }}"
    group: "{{ prom_group_name }}"
  with_items: "{{ thanos_ruler_templates | default(omit) }}"
  become: yes

