---
# file: dns_alert_rules.yml
# location: central

groups: 

- name: DNS 
  rules:

  - alert: FabricDNSDown
    expr: probe_success{job="blackbox-dns"}== 0
    for: 5m
    labels: 
      severity: critical
      fabric_response: system
    annotations:
      summary:  "DNS server {{ $labels.instance }} is down."   
      description:  "{{ $labels.instance }} has been down or not responding for more than 5 minutes." 
