---
# file: mail_alert_rules.yml
# location: all racks, central

groups: 

- name: Mail 
  rules:

  - alert: FabricMailDown
    expr: probe_success{job="smtp"}== 0
    for: 5m
    labels: 
      severity: critical
      fabric_response: system
      
    annotations:
      summary:  "Mail server {{ $labels.instance }} is down."   
      description:  "{{ $labels.instance }} has been down or not responding for more than 5 minutes." 
