---
# file: ptp_alert_rules.yml
# location: racks with PTP server

groups: 

- name: PTP Alerts
  rules: 

  - alert: RackGPSTimeUnknown
    expr: tmiGPSTimeKnown  == 0
    for: 15m
    labels:
      severity: error
      fabric_system: time
      fabric_response: hardware
    annotations:
      summary:  "GPS time is not known node at {{ $externalLabels.rack }}."   
      description:  "tmiGPSTimeKnown is 0 on {{ $externalLabels.rack }}." 

  - alert: 2DGPSFix
    expr: tmiGPSFix == 1
    for: 15m
    labels:
      severity: info
      fabric_system: time
      fabric_response: hardware
    annotations:
      summary:  "GPS time sync is only 2D on {{ $externalLabels.rack }}."   
      description:  "tmiGPSFix is 2 on {{ $externalLabels.rack }}."

  - alert: NoGPSFix
    expr: tmiGPSFix == 0
    for: 15m
    labels: 
      severity: warning
      fabric_system: time
      fabric_response: hardware
    annotations:
      summary:  "GPS time is not fixed on node {{ $externalLabels.rack }}."   
      description:  "tmiGPSFix is 0 on {{ $externalLabels.rack }}." 
      
  - alert: GPSPTPWebInterfaceDown
    expr: probe_success{job="ptp_server_ui"} == 0
    for: 15m
    labels: 
      severity: error
      fabric_system: time
      fabric_response: hardware
    annotations:
      summary:  "GPS-PTP server web ui is not responding at {{ $externalLabels.rack }}. Most likely device is down." 
      description:  "GPS-PTP server web ui has not responded for more than 15 minutes at {{ $externalLabels.rack }}. Most likely device is down."   
      
