---
# file: time_alert_rules.yml
# location: all racks

groups: 

- name: PTP Alerts
  rules: 
  
  - alert: RackNodeNotTimeSynced
    expr: node_timex_sync_status { component_type=~"head|worker" } == 0 
    for: 15m
    labels:
      severity: error
      fabric_system: time
      fabric_response: hardware
    annotations:
      summary:  "Time is not synced on node {{ $labels.instance }}, at {{ $externalLabels.rack }}."   
      description:  "node_timex_sync_status is 0 on {{ $labels.instance }}, at {{ $externalLabels.rack }}." 

  - alert: RackNodeTimexMaxErrorTooHigh
    expr: node_timex_maxerror_seconds{job="node", component_type=~"head|worker"} > 0.001
    for: 15m
    labels:
      severity: error
      fabric_system: time
      fabric_response: hardware
    annotations:
      summary:  "Timex max error exceeded on node {{ $labels.instance }}, at {{ $externalLabels.rack }}."   
      description:  "node_timex_maxerror_seconds is > 0.001 on {{ $labels.instance }}, at {{ $externalLabels.rack }}. Indicates node is not time synced." 
