---
# Create the base directories needed by snmp
- name: Create SNMP Directories
  block:
      
    - name: "Create SNMP directories"
      file:
        path: "{{ base_install_dir }}/snmp/{{ item }}"
        state: directory
        recurse: yes
        owner: "{{ prom_user_name }}"
        group: "{{ prom_group_name }}"
      with_items:
        - [ "config" ]

  become: yes