---
# Creates a secrets file for prometheus scrapes
# Uses the following variable 
# prometheus_secrets: 
#   - name: jupyterhub
#    secret:  adsjhgauifyohj
# Creates a file named secret.name which contains secret.secret


  # Add a file to the prometheus secret directory
- name: Add Prometheus Secret 
  copy:
    content: "{{ item.secret }}"
    dest: "{{ base_install_dir }}/prometheus/secrets/{{ item.name }}"
    owner: "{{ prom_user_name }}"
    group: "{{ prom_group_name }}"
  with_items: "{{ prometheus_secrets | default(omit) }}"
  become: yes