---
# Prometheus Default config file.
# Note that the template files are passed in without the .j2 suffix
- name: Prometheus configs
  block:
    - name: "Add Prometheus Config scraping file."
      copy: 
        backup: yes
        src: '{{ prometheus_templates_dir }}/default_prometheus_config.yml.j2'
        dest: "{{ base_install_dir }}/prometheus/config/prometheus_config.yml"
        owner: "{{ prom_user_name }}"
        group: "{{ prom_group_name }}"

  become: yes
