---
##############################################################
#                   Central Ping Plus                   #
##############################################################
# This section contains the tasks needed for installing the 
#   central metrics prometheus to monitor fabric wide items.
#   This includes pinging all of the avaialble infrastructure and
#   running black box probes to Fabric web sites and servers.


# will need promtehus, thanos sidecar, blackbox exporter 
#basically a rack install

- name: Stop Docker Compose 
  block:
  - name: Check if docker-compose.yml exists 
    stat: 
      path: "{{ base_install_dir }}/docker-compose.yml"
    register: docker_compose_file_status

  - name: Stop Docker compose file
    shell: docker-compose down 
    args:
      chdir: "{{ base_install_dir }}"
    when: docker_compose_file_status.stat.exists



- name: Install Fabric Central Ping-Plus setup 
  block:

  - name: Install Fabric Central Ping-Plus Metrics
    import_tasks: fabric_central_ping_plus_install_tasks.yml


##############################
#  Node Exporter Install     #
##############################
- name: Install node_exporter 
  # Install the node exporter for ping-plus vm 
  block:
  - name: Install Node_exporter
    import_tasks: install_node_exporter_tasks.yml
  when: 
    - install_node_exporters is defined
    - install_node_exporters 


- name: Add Docker Compose file 
  block:
    - name: Create docker-compose.yml 
      template:
        src: "templates/DockerCompose/docker_compose_complete.yml.j2"
        dest: "{{ base_install_dir }}/docker-compose.yml"
  become: yes


- name: Start Docker Compose 
  block:
  - name: Start Docker compose file
    shell: docker-compose up -d
    args:
      chdir: "{{ base_install_dir }}"


#TODO add check to see if containers are up