# Check if docker-compose is installed
- name: Check if Docker Compose is installed
  tags: docker-compose
  shell: command -v docker-compose >/dev/null 2>&1
  register: is_docker_compose_install

# If docker-compose is not installed, quit
- name: Exit if docker-compose is missing
  fail: msg="docker-compose is missing"
  when: is_docker_compose_install.rc != 0

# Copy required files
- name: Copy required files
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "docker-compose.yml", dest: "/opt/beats/" }
    - { src: "mfkfk1-1_fabric-testbed_net_interm.cer", dest: "/opt/beats/" }

# Copy the packetbeat.yml
- name: Copy Packetbeat template file
  tags: packetbeat
  become: true
  template:
    src: packetbeat.yml.j2
    dest: /opt/beats/packetbeat-docker.yml
# Start Packetbeat
# - name: Start Filebeat
#   tags: filebeat
#   shell: docker-compose up -d filebeat
#   args:
#     chdir: /opt/beats/
