version: "3.6"

services:
  packetbeat:
    image: docker.elastic.co/beats/packetbeat:8.6.1
    container_name: fabric_beats_packetbeat
    user: root
    command: -strict.perms=false -e
    cap_add: ["NET_RAW", "NET_ADMIN"]
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
    secrets:
      - source: packetbeat.yml
        target: /usr/share/packetbeat/packetbeat.yml
      - source: mfbr1-p_fabric-testbed_net_interm.cer
        target: /usr/share/packetbeat/certs/ca/mfbr1-p_fabric-testbed_net_interm.cer

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.6.1
    network_mode: host
    restart: always
    container_name: fabric_beats_filebeat
    user: root
    command: -strict.perms=false -e
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/:ro"
      - "/var/log/:/var/log/:ro"
      - "/opt/data/zeek/logs:/opt/zeek/logs"
      - "/opt/data/zeek/spool:/opt/zeek/spool"
      - "/home/nrig-service/ControlFramework/fabric_cf/:/home/nrig-service/ControlFramework/fabric_cf/"
    secrets:
      - source: filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
      - source: mfbr1-p_fabric-testbed_net_interm.cer
        target: /etc/filebeat/mfbr1-p_fabric-testbed_net_interm.cer

secrets:
  packetbeat.yml:
    file: ./packetbeat-docker.yml
  filebeat.yml:
    file: ./filebeat-docker.yml
  mfbr1-p_fabric-testbed_net_interm.cer:
    file: ./mfbr1-p_fabric-testbed_net_interm.cer
