---
# Install Important! This will be the base name for the install directories
#    and docker containers.
# You can change this as needed. It must be in a valid directory name format.
install_name: dev_test_prometheus
# Network
# A Docker Network is setup for all of the monitoring containers to attach to.
# run "docker network inspect <install_name>"" on the host to see what is currently attached.
docker_network_name: "{{ install_name }}"
# Install Directories
# Each container will have a diretory for configuration files.
# Containers which create a lot of data will have a data directory.
base_data_dir: "/opt/data/{{ install_name }}"
base_install_dir: "/opt/{{ install_name }}" 
# Install owner
# Files will be owned by this user.
prom_user_name: dev-prom
prom_group_name: dev-prom
    
# Locations for self signed cert creation.
# If host aleady has certs, then skip the self-signed task and
#  just use the cert on the host machine.
host_csr: /etc/ssl/private/{{ hostname }}.csr
self_signed_cert_path: /etc/test_ssl/{{ hostname }}

host_cert: /etc/test_ssl/{{ hostname }}/fullchain.pem
host_key: /etc/test_ssl/{{ hostname }}/privkey.pem

host_interm_cert: /etc/test_ssl/{{ hostname }}/fullchain.pem

# GENI Slice
# These vars are used to setup the prometheus configuration for
#  pulling node_exporters and blackbox pings.
# These will come from the inventory file later on.
geni_slice_nodes:
    - ip:  <ip address>
      name: <node name>
    #- etc....
# Template and files directories
# The following directories allow you to create
#   custom sets of configurations as needed for
#   special cases.    
# Prometheus
prometheus_files_dir: files/geni_slice
prometheus_templates_dir: templates/geni_slice

# SNMP
snmp_templates_dir: templates/geni_slice
snmp_community_string: <community string goes here>

# Blackbox
blackbox_files_dir: files
blackbox_templates_dir: templates/geni_slice

# Grafana
grafana_templates_dir: templates/Grafana

grafana_datasource_template_files:
  - grafana_local_prometheus_datasource.yml




# AlertManager
# alertmanager_template_dir: templates/geni_slice
# Port is used in prometheus config template file.
alertmanager_port: 9093
# alert_manager_slack_api_url: 

# NGINX
nginx_template_dir: templates/Nginx
#nginx_confd_templates_dir: templates/Nginx/conf.d
