---
# Changes the state of an existing container. Cannot create a new container.
# Available states are
# absent  - Removes the container and won't be able to restart.
# present - Donot user here. No real affect here since we are only operating on the container name.
# stopped - Stops existing container from running.
# started - Starts existing container running.
- name: Debug inconing vars
  debug:
    msg: "{{ new_docker_state }} {{ install_name }}_{{ item }}"
  with_items: "{{ containers_to_act_on }}"

- name: Change Docker Containers State
  community.docker.docker_container:
    state: "{{ new_docker_state }}"
    name: "{{ install_name }}_{{ item }}"
  with_items: "{{ containers_to_act_on }}"
  become: yes