# Check if docker-compose is installed
- name: Check if Docker Compose is installed
  tags: docker-compose
  shell: command -v docker-compose >/dev/null 2>&1
  register: is_docker_compose_install

# If docker-compose is not installed, quit
- name: Exit if docker-compose is missing
  fail: msg="docker-compose is missing"
  when: is_docker_compose_install.rc != 0

# # Check if the filebeat is already up and running
# - name: Check if filebeat container is up and running
#   docker_container_info:
#     name: fabric_beats_filebeat
#   register: is_docker_container_running

# - name: Print the status of container
#   fail:
#     msg: "fabric_beats_filebeat container is already up and running"
#   when: is_docker_container_running.container['State']['Status'] == "running"

# Replace rsyslog.conf file
- name: Copy Filebeat template file
  tags: rsyslog
  become: true
  template:
    src: "{{ rsyslog_conf_template_file }}"
    dest: /etc/rsyslog.conf

# Restart rsyslog
- name: Restart rsyslog
  become: true
  service:
    name: rsyslog
    state: restarted

# Rotate syslog (prevent pushing too much syslog to Kafka)
- name: Rotate syslog
  become: true
  shell: logrotate -f /etc/logrotate.d/syslog

# Copy required files
- name: Copy required files
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "docker-compose.yml", dest: "/opt/beats/" }
    - { src: "mfkfk1-1_fabric-testbed_net_interm.cer", dest: "/opt/beats/" }

# Copy the filebeat.yml
- name: Copy Filebeat template file
  tags: filebeat
  become: true
  template:
    src: filebeat.yml.j2
    dest: /opt/beats/filebeat-docker.yml

# Start Filebeat
- name: Start Filebeat
  tags: filebeat
  shell: docker-compose up -d filebeat
  args:
    chdir: /opt/beats/
