---
# This file contains the common default variables that are the same for all services.

####################
#  Node Exporter   #
####################        

node_exporter_tls_server_config:
  cert_file: /etc/node_exporter/tls.cert
  key_file: /etc/node_exporter/tls.key
node_exporter_web_listen_address: "{{ ansible_host }}:9100"




