##############################################################
#                   Thanos Compactor                         #
##############################################################
# This section contains the tasks needed for installing the 
#   thanos compactor. Note Compactor should only be run in one place.

- name: Install docker Python SDK
  ansible.builtin.pip:
    name: docker 
    executable: "{{ pip_version }}"
    state: present
  become: yes



- name: Stop Docker Compose 
  block:
  - name: Check if docker-compose.yml exists 
    stat: 
      path: "{{ base_install_dir }}/docker-compose.yml"
    register: docker_compose_file_status

  - name: Stop Docker compose file
    shell: docker-compose down 
    args:
      chdir: "{{ base_install_dir }}"
    when: docker_compose_file_status.stat.exists

####################     
#      USER        #
####################
- name: Setup user for promtheus monitoring system
  # Create a user to setup all the fab monitoring stuff under.
  # Get user uid:gid and set to vars
  include_tasks: setup_tasks/create_prom_user_tasks.yml

####################
#  DOCKER NETWORK  #
####################
# note that taking down the network may affect other containers added by other scripts 
- name: Setup the docker network to be used by the monitoring containers.
  include_tasks: setup_tasks/setup_docker_ipv6_network_tasks.yml


####################
#     THANOS       #
####################
- name: Setup Thanos
  block:
    - name: Thanos Directories
      include_tasks: Thanos/setup_thanos_directories_tasks.yml
  
    - name: Thanos Configs
      include_tasks: Thanos/add_thanos_config_templates_tasks.yml
      # See vars for templates used




- name: Add Docker Compose file 
  block:
    - name: Create docker-compose.yml 
      template:
        src: "templates/DockerCompose/docker_compose_complete.yml.j2"
        dest: "{{ base_install_dir }}/docker-compose.yml"
  become: yes


- name: Start Docker Compose 
  block:
  - name: Start Docker compose file
    shell: docker-compose up -d
    args:
      chdir: "{{ base_install_dir }}"



