# Creates the timestamp service by putting the timestamp Dockerfile on each experiment node
# Currently copies the Dockerfile from the measurement node to each experiment node and finish the build 
---
- name: Create timesatmp service
  hosts: Experiment_Nodes
  tasks:  
    - name: Create a directory for Dockerfile
      ansible.builtin.file:
        path: /home/mfuser/services/timestamp/dockerfile
        state: directory
        mode: '0755'

    - name: Copy Dockerfile
      ansible.builtin.copy:
        src: /home/mfuser/services/timestamp/files/Dockerfile
        dest: /home/mfuser/services/timestamp/dockerfile/Dockerfile
        mode: '0644'
        
    - name: Build owl container image
      community.general.docker_image:
        name: timestamp:0.1.0
        build:
          path: /home/mfuser/services/timestamp/dockerfile
          pull: true
          network: host
        source: build