# Remove timestamp docker container and image
---
- name: Remove timestamp container
  hosts: Experiment_Nodes
  tasks:
    - name: Remove timestamp container
      community.general.docker_container:
        name: timestamp
        state: absent

    - name: Remove timestamp docker image
      community.general.docker_image:
        name: timestamp
        tag: 0.1.0
        state: absent
        
    - name: Recursively remove volume directory
      ansible.builtin.file:
        path: /home/mfuser/services/timestamp/output
        state: absent

      