- name: Remove timesatmp service
  hosts: Experiment_Nodes
  tasks:
    - name: remove service directory
      file:
        state: absent
        path: /home/mfuser/services/timestamp/
      

      