- name: Start timestamp service
  hosts: Experiment_Nodes
  tasks:
    - name: Run timestampservice.py to create elasticsearch indice
      command: sudo python3 /home/mfuser/services/timestamp/service_files/timestampservice.py
   
      
      