# Start timestamp service
---
- name: Start timestamp container
  hosts: Experiment_Nodes 
  tasks:
  - name: Start timestamp container
    community.general.docker_container:
      name: timestamp
      image: timestamp:0.1.0 
      state: started
      restart: true
      privileged: true
      detach: true
      interactive: true
      tty: true
      network_mode: host
      pid_mode: host
      volumes:
        - /home/mfuser/services/timestamp/output:/root/services/timestamp/output_files
      
      