# Remove influxdb docker container and image
---
- name: Remove influxdb container
  hosts: Meas_Node
  tasks:
    - name: Remove influxdb container
      community.general.docker_container:
        name: influxdb
        state: absent

    - name: Remove influxdb docker image
      community.general.docker_image:
        name: influxdb
        tag: 2.0
        state: absent