# Start influxdb container
---
- name: Start influxdb container
  hosts: Meas_Node
  tasks:
  - name: Start influxdb container
    community.general.docker_container:
      name: influxdb
      image: influxdb:2.0 
      env:
        DOCKER_INFLUXDB_INIT_MODE: "setup"
        DOCKER_INFLUXDB_INIT_USERNAME: "my-user" 
        DOCKER_INFLUXDB_INIT_PASSWORD: "my-password" 
        DOCKER_INFLUXDB_INIT_ORG: "my-org" 
        DOCKER_INFLUXDB_INIT_BUCKET: "my-bucket" 
      state: started
      restart: true
      privileged: true
      network_mode: host
      detach: true
      volumes:
        - /home/ubuntu/influxdb:/var/lib/influxdb2