---
# Remove the base install directories for fabric prometheus system
# This removes ALL the directories under the base_install_dir.
# It does not remove the data directories unless they are also under the base_install_dir

- name: Remove Prometheus Directories
  block:
      
    - name: "Remove Prometheus directories"
      file:
        path: "{{ base_install_dir }}"
        state: absent
        owner: "{{ prom_user_name }}"
        group: "{{ prom_group_name }}"

  become: yes

