---

# Passwords will need to be set in another file.
# fabric_prometheus_ht_user: <username to access nginx proxy>
# fabric_prometheus_ht_password: <password to access nginx proxy>

# node_exporter_username: <username to access exporter metrics>
# node_exporter_password: <passord to access exporter metrics>

# snmp_community_string: <community-string>

# grafana_admin_password: <password for admin account>



# Install Important! This will be the base name for the install directories
#    and docker containers.
install_name: fabric_prometheus
# Network
docker_network_name: "{{ install_name }}"
# Install Directories
base_data_dir: "/opt/data/{{ install_name }}"
base_install_dir: "/opt/{{ install_name }}" 
# Install owner
prom_user_name: fab-prom
prom_group_name: fab-prom
    
# Locations for self signed cert creation.
# If host aleady has certs, then skip the self-signed task and
#  just use the cert on the host machine.
self_signed_cert_dir: "{{ base_install_dir }}/ssl"
self_signed_key_dir: "{{ base_install_dir }}/ssl/private"

host_csr: "{{ self_signed_cert_dir }}/{{ hostname }}.csr"
host_cert: "{{ self_signed_cert_dir }}/{{ hostname }}_fullchain.pem"
host_key: "{{ self_signed_key_dir }}//{{ hostname }}_privkey.pem"

host_interm_cert: "{{ self_signed_cert_dir }}/{{ hostname }}_fullchain.pem"


# Prometheus
#prometheus_files_dir: files/
prometheus_templates_dir: templates/Prometheus

# Docker
docker_templates_dir: templates/Docker 
# Blackbox
blackbox_files_dir: files
#blackbox_templates_dir: templates

# Grafana
grafana_templates_dir: templates/Grafana

grafana_datasource_template_files:
  - grafana_local_prometheus_datasource.yml
# grafana_dashboard_template_files:
#   - grafana_node_exporter_full_dashboard.json
#   - grafana_dashboard.yml.j2
grafana_state: started
grafana_cert:  "{{ host_cert }}"
grafana_key:  "{{ host_key }}"
grafana_user_name: grafana
grafana_user_id: 472
grafana_group_name: root  





# AlertManager
#alertmanager_template_dir: templates/geni_slice
alertmanager_port: 9093
#alert_manager_slack_api_url: 

# NGINX
nginx_template_dir: templates/Nginx

nginx_cert: "{{ host_cert }}"
nginx_key: "{{ host_key }}"
nginx_interm_cert: "{{ host_interm_cert }}"
nginx_ip_ports:
  # Note Each port will correspond to a confd file set above.
  #- 80:80         # Redirected to 443
  - 443:443       # /grafana for grafana interface
  #- 9090:9090     # prometheus stats
    





# Node Exporter
node_exporter_web_listen_address: "{{ ansible_host }}:9100"

extra_node_hosts: {}