{
 "title": "Network Traffic Dashboard",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node:  ",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "device",
    "label": "Device:",
    "query": {
     "query": "label_values(node_network_device_id, device)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network Traffic by Packets",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pps", "label": "packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{instance=\"$node\",job=\"$job\", device=\"$device\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "rate(node_network_transmit_packets_total{instance=\"$node\",job=\"$job\", device=\"$device\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  { "title": "TCP Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "TCP In / Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "datagrams out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_InSegs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "InSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "OutSegs"
    }
   ]
  },
  {
   "title": "TCP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "datagrams out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_InErrs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "$node"
    }
   ]
  },
  { "title": "UDP Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "UDP In / Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "datagrams out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Udp_InDatagrams{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "InDatagrams"
    },
    {
     "expr": "rate(node_netstat_Udp_OutDatagrams{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "OutDatagrams"
    }
   ]
  },
  {
   "title": "UDP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "datagrams out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Udp6_InErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "$node"
    }
   ]
  },
  { "title": "Network Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Network Traffic Received Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "pps", "label": "packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total{instance=\"$node\",job=\"$job\", device=\"$device\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive errors"
    }
   ]
  },
  {
   "title": "Network Traffic Send Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "pps", "label": "packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_errs_total{instance=\"$node\",job=\"$job\", device=\"$device\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Send errors"
    }
   ]
  }
 ]
}