---
  # used to turn off all worker node file beats
- hosts: Experiment_Nodes
  become: true
  tags: worker_service_management
  tasks:
    - name: Filebeat Service all workers stopped
      ansible.builtin.service:
        name: metricbeat
        state: stopped
        enabled: true # left on as default