---
# Add a *_targets.yml file to the prometheus config
# Note that the template files are passed in without the .j2 suffix
- name: Create targets file.
  template:
    backup: yes
    src: "{{ prometheus_templates_dir }}/{{ item }}.j2"
    dest: "{{ base_install_dir }}/prometheus/config/{{ item }}"
    owner: "{{ prom_user_name }}"
    group: "{{ prom_group_name }}"
  with_items: "{{ prometheus_target_templates }}"
  become: yes


