---
# Add a file to the prometheus config directory
# Warning, if prometheus_config_files is null, then this will copy all the files in
#   the prometheus_files_dir
- name: Add Prometheus Config via Files
  copy:
    src: "{{ prometheus_files_dir }}/{{ item }}"
    dest: "{{ base_install_dir }}/prometheus/config/{{ item }}"
    owner: "{{ prom_user_name }}"
    group: "{{ prom_group_name }}"
  with_items: "{{ prometheus_config_files | default(omit) }}"
  become: yes