---
# Create the base directories needed by prometheus
- name: Create Prometheus Directories
  block:
      
    - name: "Create Prometheus directories"
      file:
        path: "{{ base_install_dir }}/prometheus/{{ item }}"
        state: directory
        recurse: yes
        owner: "{{ prom_user_name }}"
        group: "{{ prom_group_name }}"
      with_items:
        - [ "config", "secrets" ]

    - name: "Create Prometheus Data directories"
      # This directory could be 10's of GB.
      file:
        path: "{{ base_data_dir }}/prometheus/data"
        state: directory
        recurse: yes
        owner: "{{ prom_user_name }}"
        group: "{{ prom_group_name }}"
  become: yes