---
# Add a template to the alertmanager directory

- name: Add Alertmanager Config File
  template:
    src: "{{ alertmanager_template_dir }}/alertmanager_config.yml.j2"
    dest: "{{ base_install_dir }}/alertmanager/alertmanager_config.yml"
    owner: "{{ prom_user_name }}"
    group: "{{ prom_group_name }}"

  become: yes