# Setup data dir
- name: Create Data Directory
  file: 
    path: /opt/data
    recurse: yes
    state: directory 
    mode: 0755
    owner: 0
    group: 0
  become: yes

- name: Create Data Partition
  community.general.parted:
    device: /dev/vdb
    number: 1
    state: present
    fs_type: ext4
    label: gpt
  become: yes

- name: Create a ext4 filesystem on /dev/vdb1
  community.general.filesystem:
    fstype: ext4 
    dev: /dev/vdb1
    state: present
  become: yes

- name: Mount As /opt/data
  ansible.posix.mount:
    path: /opt/data
    src: /dev/vdb1
    fstype: ext4
    state: mounted
  become: yes