---
# used to turn off all worker node file beats
- hosts: workers
  become: true
  tags: worker_service_management
  tasks:
    - name: Filebeat Service all workers stopped
      ansible.builtin.service:
        name: filebeat
        state: stopped
        enabled: true # left on as default

    - name: Metricbeat Service all workers stopped
      ansible.builtin.service:
        name: metricbeat
        state: stopped
        enabled: true # left on as default

    - name: Packet Service all workers stopped
      ansible.builtin.service:
        name: packetbeat
        state: stopped
        enabled: true # left on as default
