---
# used to turn off all worker node file beats
- hosts: workers
  become: true
  tags: worker_service_management
  tasks:
    - name: Packetbeat Service all workers started
      ansible.builtin.service:
        name: packetbeat
        state: started
        enabled: true # left on as default
