---
# Creating experiment slice monitoring setup.
- hosts: Meas_Node
  roles:
    - role: ../prometheus/ansible/roles/fabric_experiment
      vars:
        install_prometheus_system: true
        install_node_exporter: true

- hosts: Experiment_Nodes
  roles:
    - role: ../prometheus/ansible/roles/fabric_experiment
      tags: exporters
      vars:
        install_node_exporter: true
