---
# Creating the rack monitoring setup.
- hosts: Meas_Node
  
  roles:
    - ../prometheus/ansible/roles/fabric_experiment
  tags:
    - monitor
   

- hosts: Experiment_Nodes

  roles:
    - ../prometheus/ansible/roles/fabric_experiment
  tags: 
    - exporters
   
