# Some conifguration files are generated and saved in mf-parser repo.
# This task gets those needed files from the repo

- name: Clone mf-parser repo
  ansible.builtin.git:
    repo: git@github.com:fabric-testbed/mf-parsers.git
    #dest: /tmp/mf-parsers
    dest: tmp_deployment_files/mf-parsers
    single_branch: yes
    version: main
    force: true
    
    
