---
# - name: Clone the linuxptp repository.
#   git:
#     repo: "{{ PTP_REPO_URL }}"
#     dest: /tmp/{{ PTP_PACKAGE_NAME }}-{{ PTP_PACKAGE_TAG }}
#     version: "{{ PTP_PACKAGE_TAG }}"
#     accept_hostkey: yes
#     #depth: 1

- name: Download linuxptp
  ansible.builtin.unarchive:
    src: "{{ PTP_SOURCE_URL }}"
    dest: /tmp/
    remote_src: yes

- name: Run 'make clean' target as root
  become: True
  make:
    chdir: /tmp/{{ PTP_PACKAGE_NAME }}-{{ PTP_PACKAGE_VERSION }}
    target: clean

- name: Run 'make install' target as root
  become: True
  make:
    chdir: /tmp/{{ PTP_PACKAGE_NAME }}-{{ PTP_PACKAGE_VERSION }}
    target: install
    params:
      prefix: '/usr'

# - name: Install linuxptp
#   package:
#     name: linuxptp