---
# Add a thanos config files 
# Note that the template files are passed in without the .j2 suffix
- name: Create config file.
  template:
    backup: yes
    src: "{{ thanos_templates_dir }}/{{ item }}.j2"
    dest: "{{ base_install_dir }}/thanos/config/{{ item }}"
    owner: "{{ prom_user_name }}"
    group: "{{ prom_group_name }}"
  with_items: "{{ thanos_config_templates }}"
  become: yes


