---
# Grafana has limited configs
# - env file to enable custom ini
# - custom ini
- name: Grafana configs
  block:
    - name: "Add Grafana custom ini."
      template: 
        backup: yes
        src: '{{ grafana_templates_dir }}/grafana_custom.ini.j2'
        dest: "{{ base_install_dir }}/grafana/custom/custom.ini"
        owner: "{{ grafana_user_name }}"
        group: "{{ grafana_group_name }}"

    - name: "Add Grafana docker env file to enable above custom ini."
      template: 
        backup: yes
        src: '{{ grafana_templates_dir }}/grafana_env.j2'
        dest: "{{ base_install_dir }}/grafana/env_file"
        owner: "{{ grafana_user_name }}"
        group: "{{ grafana_group_name }}"
  become: yes
