---
# Create self-signed certs for testing and machines that don't have official certs or
#  for times we just need a cert for TLS.

    - name: Generate a Self Signed OpenSSL certificate 
      block:

      - name: Create Directories for certs
        file: 
          path: "{{ self_signed_cert_dir }}"
          recurse: yes
          state: directory 
          mode: 755
          owner: "{{ prom_user_name }}"
          group: "{{ prom_group_name }}"
        become: yes

      - name: Create Directories for keys
        file: 
          path: "{{ self_signed_key_dir }}"
          recurse: yes
          state: directory 
          mode: 710
          owner: "{{ prom_user_name }}"
          group: "{{ prom_group_name }}"
        become: yes

      - name: Generate an OpenSSL private key.
        community.crypto.openssl_privatekey:
          path: "{{ host_key }}"
        become: yes
          
      - name: Generate an OpenSSL CSR.
        community.crypto.openssl_csr:
          path: "{{ host_csr }}"
          privatekey_path: "{{ host_key }}"
          common_name: "{{ hostname }}"
        become: yes

      - name: Generate a Self Signed OpenSSL certificate.
        #openssl_certificate:
        community.crypto.x509_certificate:
          path: "{{ host_cert }}"
          privatekey_path: "{{ host_key }}"
          csr_path: "{{ host_csr }}"
          provider: selfsigned
          selfsigned_not_after: "+365d"
      become: yes
